# coding: utf-8

# (C) Copyright IBM Corp. 2026.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# IBM OpenAPI SDK Code Generator Version: 3.113.1-d76630af-20260320-135953

"""
No description provided (generated by Openapi Generator
https://github.com/openapitools/openapi-generator)

API Version: 1.0.0
"""

from datetime import datetime
from typing import Dict, List, Optional
import json

from ibm_cloud_sdk_core import BaseService, DetailedResponse
from ibm_cloud_sdk_core.authenticators.authenticator import Authenticator
from ibm_cloud_sdk_core.get_authenticator import get_authenticator_from_environment
from ibm_cloud_sdk_core.utils import datetime_to_string, string_to_datetime

from .common import get_sdk_headers

##############################################################################
# Service
##############################################################################


class PowerhaAutomationServiceV1(BaseService):
    """The PowerhaAutomation Service V1 service."""

    DEFAULT_SERVICE_URL = 'https://power-dra.cloud.ibm.com'
    DEFAULT_SERVICE_NAME = 'powerha_automation_service'

    @classmethod
    def new_instance(
        cls,
        service_name: str = DEFAULT_SERVICE_NAME,
    ) -> 'PowerhaAutomationServiceV1':
        """
        Return a new client for the PowerhaAutomation Service service using the
               specified parameters and external configuration.
        """
        authenticator = get_authenticator_from_environment(service_name)
        service = cls(authenticator)
        service.configure_service(service_name)
        return service

    def __init__(
        self,
        authenticator: Authenticator = None,
    ) -> None:
        """
        Construct a new client for the PowerhaAutomation Service service.

        :param Authenticator authenticator: The authenticator specifies the authentication mechanism.
               Get up to date information from https://github.com/IBM/python-sdk-core/blob/main/README.md
               about initializing the authenticator of your choice.
        """
        BaseService.__init__(self, service_url=self.DEFAULT_SERVICE_URL, authenticator=authenticator)

    #########################
    # PowerhaAutomationConfig
    #########################

    def create_api_key(
        self,
        pha_instance_id: str,
        *,
        api_key: Optional[str] = None,
        accept_language: Optional[str] = None,
        **kwargs,
    ) -> DetailedResponse:
        """
        Update the apikey for the specified PowerHA service instance.

        Updates a new apikey for the specified PowerHA service instance.

        :param str pha_instance_id: Unique identifier of the provisioned instance.
        :param str api_key: (optional) The API key to be stored or registered.
        :param str accept_language: (optional) The language requested for the
               return document.
        :param dict headers: A `dict` containing the request headers
        :return: A `DetailedResponse` containing the result, headers and HTTP status code.
        :rtype: DetailedResponse with `dict` result representing a `ApiKeyResponse` object
        """

        if not pha_instance_id:
            raise ValueError('pha_instance_id must be provided')
        headers = {
            'Accept-Language': accept_language,
        }
        sdk_headers = get_sdk_headers(
            service_name=self.DEFAULT_SERVICE_NAME,
            service_version='V1',
            operation_id='create_api_key',
        )
        headers.update(sdk_headers)

        data = {
            'api_key': api_key,
        }
        data = {k: v for (k, v) in data.items() if v is not None}
        data = json.dumps(data)
        headers['content-type'] = 'application/json'

        if 'headers' in kwargs:
            headers.update(kwargs.get('headers'))
            del kwargs['headers']
        headers['Accept'] = 'application/json'

        path_param_keys = ['pha_instance_id']
        path_param_values = self.encode_path_vars(pha_instance_id)
        path_param_dict = dict(zip(path_param_keys, path_param_values))
        url = '/powerha_automation/v1/api_key/{pha_instance_id}'.format(**path_param_dict)
        request = self.prepare_request(
            method='POST',
            url=url,
            headers=headers,
            data=data,
        )

        response = self.send(request, **kwargs)
        return response

    def get_cluster_node(
        self,
        pha_instance_id: str,
        *,
        if_none_match: Optional[str] = None,
        **kwargs,
    ) -> DetailedResponse:
        """
        Retrieves the cluster node details for the specified PowerHA instance.

        Retrieves details of all cluster nodes configured for the given PowerHA service
        instance.

        :param str pha_instance_id: Unique identifier of the provisioned instance.
        :param str if_none_match: (optional) ETag for conditional requests
               (optional).
        :param dict headers: A `dict` containing the request headers
        :return: A `DetailedResponse` containing the result, headers and HTTP status code.
        :rtype: DetailedResponse with `dict` result representing a `ClusterNodeResponse` object
        """

        if not pha_instance_id:
            raise ValueError('pha_instance_id must be provided')
        headers = {
            'If-None-Match': if_none_match,
        }
        sdk_headers = get_sdk_headers(
            service_name=self.DEFAULT_SERVICE_NAME,
            service_version='V1',
            operation_id='get_cluster_node',
        )
        headers.update(sdk_headers)

        if 'headers' in kwargs:
            headers.update(kwargs.get('headers'))
            del kwargs['headers']
        headers['Accept'] = 'application/json'

        path_param_keys = ['pha_instance_id']
        path_param_values = self.encode_path_vars(pha_instance_id)
        path_param_dict = dict(zip(path_param_keys, path_param_values))
        url = '/powerha_automation/v1/cluster_nodes/{pha_instance_id}'.format(**path_param_dict)
        request = self.prepare_request(
            method='GET',
            url=url,
            headers=headers,
        )

        response = self.send(request, **kwargs)
        return response

    def create_cluster_node(
        self,
        pha_instance_id: str,
        primary_cluster_nodes: List[str],
        *,
        secondary_cluster_nodes: Optional[List[str]] = None,
        accept_language: Optional[str] = None,
        if_none_match: Optional[str] = None,
        **kwargs,
    ) -> DetailedResponse:
        """
        Add a new cluster node.

        Adds a new node to the PowerHA cluster for the specified PowerHA service instance.

        :param str pha_instance_id: Unique identifier of the provisioned instance.
        :param List[str] primary_cluster_nodes: List of primary cluster node VM
               IDs.
        :param List[str] secondary_cluster_nodes: (optional) List of secondary
               cluster node VM IDs.
        :param str accept_language: (optional) The language requested for the
               return document.
        :param str if_none_match: (optional) ETag for conditional requests
               (optional).
        :param dict headers: A `dict` containing the request headers
        :return: A `DetailedResponse` containing the result, headers and HTTP status code.
        :rtype: DetailedResponse with `dict` result representing a `ClusterNodeResponse` object
        """

        if not pha_instance_id:
            raise ValueError('pha_instance_id must be provided')
        if primary_cluster_nodes is None:
            raise ValueError('primary_cluster_nodes must be provided')
        headers = {
            'Accept-Language': accept_language,
            'If-None-Match': if_none_match,
        }
        sdk_headers = get_sdk_headers(
            service_name=self.DEFAULT_SERVICE_NAME,
            service_version='V1',
            operation_id='create_cluster_node',
        )
        headers.update(sdk_headers)

        data = {
            'primary_cluster_nodes': primary_cluster_nodes,
            'secondary_cluster_nodes': secondary_cluster_nodes,
        }
        data = {k: v for (k, v) in data.items() if v is not None}
        data = json.dumps(data)
        headers['content-type'] = 'application/json'

        if 'headers' in kwargs:
            headers.update(kwargs.get('headers'))
            del kwargs['headers']
        headers['Accept'] = 'application/json'

        path_param_keys = ['pha_instance_id']
        path_param_values = self.encode_path_vars(pha_instance_id)
        path_param_dict = dict(zip(path_param_keys, path_param_values))
        url = '/powerha_automation/v1/cluster_nodes/{pha_instance_id}'.format(**path_param_dict)
        request = self.prepare_request(
            method='POST',
            url=url,
            headers=headers,
            data=data,
        )

        response = self.send(request, **kwargs)
        return response

    def delete_cluster_node(
        self,
        pha_instance_id: str,
        vm_id: str,
        *,
        if_none_match: Optional[str] = None,
        **kwargs,
    ) -> DetailedResponse:
        """
        Delete a cluster node.

        Removes the specified cluster node from the PowerHA service instance.

        :param str pha_instance_id: Unique identifier of the provisioned instance.
        :param str vm_id: vm ID of workspace.
        :param str if_none_match: (optional) ETag for conditional requests
               (optional).
        :param dict headers: A `dict` containing the request headers
        :return: A `DetailedResponse` containing the result, headers and HTTP status code.
        :rtype: DetailedResponse with `dict` result representing a `ClusterNodeResponse` object
        """

        if not pha_instance_id:
            raise ValueError('pha_instance_id must be provided')
        if not vm_id:
            raise ValueError('vm_id must be provided')
        headers = {
            'If-None-Match': if_none_match,
        }
        sdk_headers = get_sdk_headers(
            service_name=self.DEFAULT_SERVICE_NAME,
            service_version='V1',
            operation_id='delete_cluster_node',
        )
        headers.update(sdk_headers)

        params = {
            'vm_id': vm_id,
        }

        if 'headers' in kwargs:
            headers.update(kwargs.get('headers'))
            del kwargs['headers']
        headers['Accept'] = 'application/json'

        path_param_keys = ['pha_instance_id']
        path_param_values = self.encode_path_vars(pha_instance_id)
        path_param_dict = dict(zip(path_param_keys, path_param_values))
        url = '/powerha_automation/v1/cluster_nodes/{pha_instance_id}'.format(**path_param_dict)
        request = self.prepare_request(
            method='DELETE',
            url=url,
            headers=headers,
            params=params,
        )

        response = self.send(request, **kwargs)
        return response

    def get_powervs_workspace(
        self,
        pha_instance_id: str,
        location_id: str,
        *,
        accept_language: Optional[str] = None,
        if_none_match: Optional[str] = None,
        **kwargs,
    ) -> DetailedResponse:
        """
        List of PowerVS workspaces based on location.

        Retrieves list of powerVS workspaces related to the PowerHA service instance based
        on location.

        :param str pha_instance_id: Unique identifier of the provisioned instance.
        :param str location_id: Location ID value.
        :param str accept_language: (optional) The language requested for the
               return document.
        :param str if_none_match: (optional) ETag for conditional requests
               (optional).
        :param dict headers: A `dict` containing the request headers
        :return: A `DetailedResponse` containing the result, headers and HTTP status code.
        :rtype: DetailedResponse with `dict` result representing a `PhaWorkspacesRegionResponse` object
        """

        if not pha_instance_id:
            raise ValueError('pha_instance_id must be provided')
        if not location_id:
            raise ValueError('location_id must be provided')
        headers = {
            'Accept-Language': accept_language,
            'If-None-Match': if_none_match,
        }
        sdk_headers = get_sdk_headers(
            service_name=self.DEFAULT_SERVICE_NAME,
            service_version='V1',
            operation_id='get_powervs_workspace',
        )
        headers.update(sdk_headers)

        params = {
            'location_id': location_id,
        }

        if 'headers' in kwargs:
            headers.update(kwargs.get('headers'))
            del kwargs['headers']
        headers['Accept'] = 'application/json'

        path_param_keys = ['pha_instance_id']
        path_param_values = self.encode_path_vars(pha_instance_id)
        path_param_dict = dict(zip(path_param_keys, path_param_values))
        url = '/powerha_automation/v1/powervs_workspaces/{pha_instance_id}'.format(**path_param_dict)
        request = self.prepare_request(
            method='GET',
            url=url,
            headers=headers,
            params=params,
        )

        response = self.send(request, **kwargs)
        return response

    #########################
    # PowerhaAutomationServiceInstance
    #########################

    def get_pha_last_operation(
        self,
        pha_instance_id: str,
        *,
        accept_language: Optional[str] = None,
        if_none_match: Optional[str] = None,
        **kwargs,
    ) -> DetailedResponse:
        """
        View details of the last operation performed on the PowerHA instance.

        Retrieves the most recent operation performed on the PowerHA service instance.

        :param str pha_instance_id: Unique identifier of the provisioned instance.
        :param str accept_language: (optional) The language requested for the
               return document.
        :param str if_none_match: (optional) ETag for conditional requests
               (optional).
        :param dict headers: A `dict` containing the request headers
        :return: A `DetailedResponse` containing the result, headers and HTTP status code.
        :rtype: DetailedResponse with `dict` result representing a `ServiceInstancePhaStatus` object
        """

        if not pha_instance_id:
            raise ValueError('pha_instance_id must be provided')
        headers = {
            'Accept-Language': accept_language,
            'If-None-Match': if_none_match,
        }
        sdk_headers = get_sdk_headers(
            service_name=self.DEFAULT_SERVICE_NAME,
            service_version='V1',
            operation_id='get_pha_last_operation',
        )
        headers.update(sdk_headers)

        if 'headers' in kwargs:
            headers.update(kwargs.get('headers'))
            del kwargs['headers']
        headers['Accept'] = 'application/json'

        path_param_keys = ['pha_instance_id']
        path_param_values = self.encode_path_vars(pha_instance_id)
        path_param_dict = dict(zip(path_param_keys, path_param_values))
        url = '/powerha_automation/v1/last_operation/{pha_instance_id}'.format(**path_param_dict)
        request = self.prepare_request(
            method='GET',
            url=url,
            headers=headers,
        )

        response = self.send(request, **kwargs)
        return response

    def get_pha_deployment(
        self,
        pha_instance_id: str,
        *,
        if_none_match: Optional[str] = None,
        **kwargs,
    ) -> DetailedResponse:
        """
        Retrieves deployment details.

        Retrieves the PowerHA deployment configuration, status, and associated metadata.

        :param str pha_instance_id: Unique identifier of the provisioned instance.
        :param str if_none_match: (optional) ETag for conditional requests
               (optional).
        :param dict headers: A `dict` containing the request headers
        :return: A `DetailedResponse` containing the result, headers and HTTP status code.
        :rtype: DetailedResponse with `dict` result representing a `PhaDeploymentResponse` object
        """

        if not pha_instance_id:
            raise ValueError('pha_instance_id must be provided')
        headers = {
            'If-None-Match': if_none_match,
        }
        sdk_headers = get_sdk_headers(
            service_name=self.DEFAULT_SERVICE_NAME,
            service_version='V1',
            operation_id='get_pha_deployment',
        )
        headers.update(sdk_headers)

        if 'headers' in kwargs:
            headers.update(kwargs.get('headers'))
            del kwargs['headers']
        headers['Accept'] = 'application/json'

        path_param_keys = ['pha_instance_id']
        path_param_values = self.encode_path_vars(pha_instance_id)
        path_param_dict = dict(zip(path_param_keys, path_param_values))
        url = '/powerha_automation/v1/pha_deployment/{pha_instance_id}'.format(**path_param_dict)
        request = self.prepare_request(
            method='GET',
            url=url,
            headers=headers,
        )

        response = self.send(request, **kwargs)
        return response

    def create_pha_deployment(
        self,
        pha_instance_id: str,
        location_id: str,
        primary_workspace: str,
        *,
        api_key: Optional[str] = None,
        cluster_type: Optional[str] = None,
        configure_type: Optional[str] = None,
        primary_cluster_nodes: Optional[List[str]] = None,
        standby_cluster_nodes: Optional[List[str]] = None,
        primary_location: Optional[str] = None,
        secondary_location: Optional[str] = None,
        secondary_workspace: Optional[str] = None,
        accept_language: Optional[str] = None,
        if_none_match: Optional[str] = None,
        **kwargs,
    ) -> DetailedResponse:
        """
        Create a new deployment.

        Create a new PowerHA deployment for a given location and PowerVS workspace. Refer
        deploying the PowerHA on Powervs
        https://cloud.ibm.com/docs/dr-automation-powervs?topic=dr-automation-powervs-getting-started-with-ha-automation-for-power-virtual-server
        for more details.

        :param str pha_instance_id: Unique identifier of the provisioned instance.
        :param str location_id: Identifier for the deployment location.
        :param str primary_workspace: Primary workspace identifier.
        :param str api_key: (optional) The API key associated with the request.
        :param str cluster_type: (optional) Type of PowerHA cluster being deployed.
        :param str configure_type: (optional) Configuration type for the
               deployment.
        :param List[str] primary_cluster_nodes: (optional) List of primary cluster
               node VM IDs.
        :param List[str] standby_cluster_nodes: (optional) List of standby cluster
               node VM IDs.
        :param str primary_location: (optional) Location identifier for the primary
               cluster.
        :param str secondary_location: (optional) Location identifier for the
               secondary cluster.
        :param str secondary_workspace: (optional) Secondary workspace identifier.
        :param str accept_language: (optional) The language requested for the
               return document.
        :param str if_none_match: (optional) ETag for conditional requests
               (optional).
        :param dict headers: A `dict` containing the request headers
        :return: A `DetailedResponse` containing the result, headers and HTTP status code.
        :rtype: DetailedResponse with `dict` result representing a `PhaDeploymentResponse` object
        """

        if not pha_instance_id:
            raise ValueError('pha_instance_id must be provided')
        if location_id is None:
            raise ValueError('location_id must be provided')
        if primary_workspace is None:
            raise ValueError('primary_workspace must be provided')
        headers = {
            'Accept-Language': accept_language,
            'If-None-Match': if_none_match,
        }
        sdk_headers = get_sdk_headers(
            service_name=self.DEFAULT_SERVICE_NAME,
            service_version='V1',
            operation_id='create_pha_deployment',
        )
        headers.update(sdk_headers)

        data = {
            'location_id': location_id,
            'primary_workspace': primary_workspace,
            'api_key': api_key,
            'cluster_type': cluster_type,
            'configure_type': configure_type,
            'primary_cluster_nodes': primary_cluster_nodes,
            'standby_cluster_nodes': standby_cluster_nodes,
            'primary_location': primary_location,
            'secondary_location': secondary_location,
            'secondary_workspace': secondary_workspace,
        }
        data = {k: v for (k, v) in data.items() if v is not None}
        data = json.dumps(data)
        headers['content-type'] = 'application/json'

        if 'headers' in kwargs:
            headers.update(kwargs.get('headers'))
            del kwargs['headers']
        headers['Accept'] = 'application/json'

        path_param_keys = ['pha_instance_id']
        path_param_values = self.encode_path_vars(pha_instance_id)
        path_param_dict = dict(zip(path_param_keys, path_param_values))
        url = '/powerha_automation/v1/pha_deployment/{pha_instance_id}'.format(**path_param_dict)
        request = self.prepare_request(
            method='POST',
            url=url,
            headers=headers,
            data=data,
        )

        response = self.send(request, **kwargs)
        return response

    #########################
    # PowerhaAutomationIbmCloud
    #########################

    def get_supported_location(
        self,
        pha_instance_id: str,
        *,
        if_none_match: Optional[str] = None,
        **kwargs,
    ) -> DetailedResponse:
        """
        Get PowerVS locations.

        Retrieves the list of PowerVS locations where PowerHA service is supported.

        :param str pha_instance_id: Unique identifier of the provisioned instance.
        :param str if_none_match: (optional) ETag for conditional requests
               (optional).
        :param dict headers: A `dict` containing the request headers
        :return: A `DetailedResponse` containing the result, headers and HTTP status code.
        :rtype: DetailedResponse with `dict` result representing a `PhaSupportedLocationsResponse` object
        """

        if not pha_instance_id:
            raise ValueError('pha_instance_id must be provided')
        headers = {
            'If-None-Match': if_none_match,
        }
        sdk_headers = get_sdk_headers(
            service_name=self.DEFAULT_SERVICE_NAME,
            service_version='V1',
            operation_id='get_supported_location',
        )
        headers.update(sdk_headers)

        if 'headers' in kwargs:
            headers.update(kwargs.get('headers'))
            del kwargs['headers']
        headers['Accept'] = 'application/json'

        path_param_keys = ['pha_instance_id']
        path_param_values = self.encode_path_vars(pha_instance_id)
        path_param_dict = dict(zip(path_param_keys, path_param_values))
        url = '/powerha_automation/v1/supported_locations/{pha_instance_id}'.format(**path_param_dict)
        request = self.prepare_request(
            method='GET',
            url=url,
            headers=headers,
        )

        response = self.send(request, **kwargs)
        return response

    #########################
    # PowerhaAutomationAgent
    #########################

    def get_pha_agent_file_download_job_status(
        self,
        pha_instance_id: str,
        pha_job_id: str,
        *,
        accept_language: Optional[str] = None,
        if_none_match: Optional[str] = None,
        **kwargs,
    ) -> DetailedResponse:
        """
        Get the Job status of the downloaded powerHA agent file.

        Returns the current status of the job associated with a PowerHA agent file
        download. It indicates whether the download job is in running, completed, or
        failed, along with relevant metadata such as job ID, Job creation time and last
        updated time.

        :param str pha_instance_id: Unique identifier of the provisioned instance.
        :param str pha_job_id: Unique ID to track the pha agent file download.
        :param str accept_language: (optional) The language requested for the
               return document.
        :param str if_none_match: (optional) ETag for conditional requests
               (optional).
        :param dict headers: A `dict` containing the request headers
        :return: A `DetailedResponse` containing the result, headers and HTTP status code.
        :rtype: DetailedResponse with `dict` result representing a `PhaAgentJobStatusResponse` object
        """

        if not pha_instance_id:
            raise ValueError('pha_instance_id must be provided')
        if not pha_job_id:
            raise ValueError('pha_job_id must be provided')
        headers = {
            'Accept-Language': accept_language,
            'If-None-Match': if_none_match,
        }
        sdk_headers = get_sdk_headers(
            service_name=self.DEFAULT_SERVICE_NAME,
            service_version='V1',
            operation_id='get_pha_agent_file_download_job_status',
        )
        headers.update(sdk_headers)

        if 'headers' in kwargs:
            headers.update(kwargs.get('headers'))
            del kwargs['headers']
        headers['Accept'] = 'application/json'

        path_param_keys = ['pha_instance_id', 'pha_job_id']
        path_param_values = self.encode_path_vars(pha_instance_id, pha_job_id)
        path_param_dict = dict(zip(path_param_keys, path_param_values))
        url = '/powerha_automation/v1/pha_agent/download/{pha_instance_id}/jobs/{pha_job_id}'.format(**path_param_dict)
        request = self.prepare_request(
            method='GET',
            url=url,
            headers=headers,
        )

        response = self.send(request, **kwargs)
        return response

    def download_pha_agent_file(
        self,
        pha_instance_id: str,
        *,
        accept_language: Optional[str] = None,
        if_none_match: Optional[str] = None,
        **kwargs,
    ) -> DetailedResponse:
        """
        Downloads PowerHA Agent file.

        Validates the pvm instance and then creates a job for the download process,
        downloads the PowerHA agent file from the Cloud Object Storage (COS) location, and
        updates the job progress in real time. Users can use the job ID to query the
        download status, including whether the job is running, completed, or failed.

        :param str pha_instance_id: Unique identifier of the provisioned instance.
        :param str accept_language: (optional) The language requested for the
               return document.
        :param str if_none_match: (optional) ETag for conditional requests
               (optional).
        :param dict headers: A `dict` containing the request headers
        :return: A `DetailedResponse` containing the result, headers and HTTP status code.
        :rtype: DetailedResponse with `BinaryIO` result
        """

        if not pha_instance_id:
            raise ValueError('pha_instance_id must be provided')
        headers = {
            'Accept-Language': accept_language,
            'If-None-Match': if_none_match,
        }
        sdk_headers = get_sdk_headers(
            service_name=self.DEFAULT_SERVICE_NAME,
            service_version='V1',
            operation_id='download_pha_agent_file',
        )
        headers.update(sdk_headers)

        if 'headers' in kwargs:
            headers.update(kwargs.get('headers'))
            del kwargs['headers']
        headers['Accept'] = 'application/octet-stream'

        path_param_keys = ['pha_instance_id']
        path_param_values = self.encode_path_vars(pha_instance_id)
        path_param_dict = dict(zip(path_param_keys, path_param_values))
        url = '/powerha_automation/v1/pha_agent/download/{pha_instance_id}'.format(**path_param_dict)
        request = self.prepare_request(
            method='GET',
            url=url,
            headers=headers,
        )

        response = self.send(request, **kwargs)
        return response


##############################################################################
# Models
##############################################################################


class ApiKeyResponse:
    """
    Response containing details of a stored API key.

    :param str status: Status of the API key retrieval request.
    :param str id: Unique identifier for the API key record.
    """

    def __init__(
        self,
        status: str,
        id: str,
    ) -> None:
        """
        Initialize a ApiKeyResponse object.

        :param str status: Status of the API key retrieval request.
        :param str id: Unique identifier for the API key record.
        """
        self.status = status
        self.id = id

    @classmethod
    def from_dict(cls, _dict: Dict) -> 'ApiKeyResponse':
        """Initialize a ApiKeyResponse object from a json dictionary."""
        args = {}
        if (status := _dict.get('status')) is not None:
            args['status'] = status
        else:
            raise ValueError('Required property \'status\' not present in ApiKeyResponse JSON')
        if (id := _dict.get('id')) is not None:
            args['id'] = id
        else:
            raise ValueError('Required property \'id\' not present in ApiKeyResponse JSON')
        return cls(**args)

    @classmethod
    def _from_dict(cls, _dict):
        """Initialize a ApiKeyResponse object from a json dictionary."""
        return cls.from_dict(_dict)

    def to_dict(self) -> Dict:
        """Return a json dictionary representing this model."""
        _dict = {}
        if hasattr(self, 'status') and self.status is not None:
            _dict['status'] = self.status
        if hasattr(self, 'id') and self.id is not None:
            _dict['id'] = self.id
        return _dict

    def _to_dict(self):
        """Return a json dictionary representing this model."""
        return self.to_dict()

    def __str__(self) -> str:
        """Return a `str` version of this ApiKeyResponse object."""
        return json.dumps(self.to_dict(), indent=2)

    def __eq__(self, other: 'ApiKeyResponse') -> bool:
        """Return `true` when self and other are equal, false otherwise."""
        if not isinstance(other, self.__class__):
            return False
        return self.__dict__ == other.__dict__

    def __ne__(self, other: 'ApiKeyResponse') -> bool:
        """Return `true` when self and other are not equal, false otherwise."""
        return not self == other


class ClusterNodeInfo:
    """
    Information about a cluster node participating in the PHA environment.

    :param str agent_status: (optional) Status of the PHA agent running on the node.
    :param float cores: (optional) Number of CPU cores allocated to the node.
    :param str ip_address: (optional) IP address assigned to the virtual machine.
    :param int memory: (optional) Memory allocated to the virtual machine in MB or
          GB.
    :param str pha_level: (optional) PowerHA version level installed on the node.
    :param str region: (optional) Region where the virtual machine is deployed.
    :param str vm_id: (optional) Unique identifier of the virtual machine.
    :param str vm_name: (optional) Name of the virtual machine.
    :param str vm_status: (optional) Current operational status of the virtual
          machine.
    :param str workspace_id: (optional) Workspace identifier associated with the
          node.
    """

    def __init__(
        self,
        *,
        agent_status: Optional[str] = None,
        cores: Optional[float] = None,
        ip_address: Optional[str] = None,
        memory: Optional[int] = None,
        pha_level: Optional[str] = None,
        region: Optional[str] = None,
        vm_id: Optional[str] = None,
        vm_name: Optional[str] = None,
        vm_status: Optional[str] = None,
        workspace_id: Optional[str] = None,
    ) -> None:
        """
        Initialize a ClusterNodeInfo object.

        :param str agent_status: (optional) Status of the PHA agent running on the
               node.
        :param float cores: (optional) Number of CPU cores allocated to the node.
        :param str ip_address: (optional) IP address assigned to the virtual
               machine.
        :param int memory: (optional) Memory allocated to the virtual machine in MB
               or GB.
        :param str pha_level: (optional) PowerHA version level installed on the
               node.
        :param str region: (optional) Region where the virtual machine is deployed.
        :param str vm_id: (optional) Unique identifier of the virtual machine.
        :param str vm_name: (optional) Name of the virtual machine.
        :param str vm_status: (optional) Current operational status of the virtual
               machine.
        :param str workspace_id: (optional) Workspace identifier associated with
               the node.
        """
        self.agent_status = agent_status
        self.cores = cores
        self.ip_address = ip_address
        self.memory = memory
        self.pha_level = pha_level
        self.region = region
        self.vm_id = vm_id
        self.vm_name = vm_name
        self.vm_status = vm_status
        self.workspace_id = workspace_id

    @classmethod
    def from_dict(cls, _dict: Dict) -> 'ClusterNodeInfo':
        """Initialize a ClusterNodeInfo object from a json dictionary."""
        args = {}
        if (agent_status := _dict.get('agent_status')) is not None:
            args['agent_status'] = agent_status
        if (cores := _dict.get('cores')) is not None:
            args['cores'] = cores
        if (ip_address := _dict.get('ip_address')) is not None:
            args['ip_address'] = ip_address
        if (memory := _dict.get('memory')) is not None:
            args['memory'] = memory
        if (pha_level := _dict.get('pha_level')) is not None:
            args['pha_level'] = pha_level
        if (region := _dict.get('region')) is not None:
            args['region'] = region
        if (vm_id := _dict.get('vm_id')) is not None:
            args['vm_id'] = vm_id
        if (vm_name := _dict.get('vm_name')) is not None:
            args['vm_name'] = vm_name
        if (vm_status := _dict.get('vm_status')) is not None:
            args['vm_status'] = vm_status
        if (workspace_id := _dict.get('workspace_id')) is not None:
            args['workspace_id'] = workspace_id
        return cls(**args)

    @classmethod
    def _from_dict(cls, _dict):
        """Initialize a ClusterNodeInfo object from a json dictionary."""
        return cls.from_dict(_dict)

    def to_dict(self) -> Dict:
        """Return a json dictionary representing this model."""
        _dict = {}
        if hasattr(self, 'agent_status') and self.agent_status is not None:
            _dict['agent_status'] = self.agent_status
        if hasattr(self, 'cores') and self.cores is not None:
            _dict['cores'] = self.cores
        if hasattr(self, 'ip_address') and self.ip_address is not None:
            _dict['ip_address'] = self.ip_address
        if hasattr(self, 'memory') and self.memory is not None:
            _dict['memory'] = self.memory
        if hasattr(self, 'pha_level') and self.pha_level is not None:
            _dict['pha_level'] = self.pha_level
        if hasattr(self, 'region') and self.region is not None:
            _dict['region'] = self.region
        if hasattr(self, 'vm_id') and self.vm_id is not None:
            _dict['vm_id'] = self.vm_id
        if hasattr(self, 'vm_name') and self.vm_name is not None:
            _dict['vm_name'] = self.vm_name
        if hasattr(self, 'vm_status') and self.vm_status is not None:
            _dict['vm_status'] = self.vm_status
        if hasattr(self, 'workspace_id') and self.workspace_id is not None:
            _dict['workspace_id'] = self.workspace_id
        return _dict

    def _to_dict(self):
        """Return a json dictionary representing this model."""
        return self.to_dict()

    def __str__(self) -> str:
        """Return a `str` version of this ClusterNodeInfo object."""
        return json.dumps(self.to_dict(), indent=2)

    def __eq__(self, other: 'ClusterNodeInfo') -> bool:
        """Return `true` when self and other are equal, false otherwise."""
        if not isinstance(other, self.__class__):
            return False
        return self.__dict__ == other.__dict__

    def __ne__(self, other: 'ClusterNodeInfo') -> bool:
        """Return `true` when self and other are not equal, false otherwise."""
        return not self == other


class ClusterNodeResponse:
    """
    Response schema for retrieving cluster node information.

    :param str id: (optional) Identifier for this cluster node response.
    :param List[NodeDetail] primary_node_details: Details of the primary cluster
          nodes.
    :param List[NodeDetail] secondary_node_details: Details of the secondary cluster
          nodes.
    """

    def __init__(
        self,
        primary_node_details: List['NodeDetail'],
        secondary_node_details: List['NodeDetail'],
        *,
        id: Optional[str] = None,
    ) -> None:
        """
        Initialize a ClusterNodeResponse object.

        :param List[NodeDetail] primary_node_details: Details of the primary
               cluster nodes.
        :param List[NodeDetail] secondary_node_details: Details of the secondary
               cluster nodes.
        :param str id: (optional) Identifier for this cluster node response.
        """
        self.id = id
        self.primary_node_details = primary_node_details
        self.secondary_node_details = secondary_node_details

    @classmethod
    def from_dict(cls, _dict: Dict) -> 'ClusterNodeResponse':
        """Initialize a ClusterNodeResponse object from a json dictionary."""
        args = {}
        if (id := _dict.get('id')) is not None:
            args['id'] = id
        if (primary_node_details := _dict.get('primary_node_details')) is not None:
            args['primary_node_details'] = [NodeDetail.from_dict(v) for v in primary_node_details]
        else:
            raise ValueError('Required property \'primary_node_details\' not present in ClusterNodeResponse JSON')
        if (secondary_node_details := _dict.get('secondary_node_details')) is not None:
            args['secondary_node_details'] = [NodeDetail.from_dict(v) for v in secondary_node_details]
        else:
            raise ValueError('Required property \'secondary_node_details\' not present in ClusterNodeResponse JSON')
        return cls(**args)

    @classmethod
    def _from_dict(cls, _dict):
        """Initialize a ClusterNodeResponse object from a json dictionary."""
        return cls.from_dict(_dict)

    def to_dict(self) -> Dict:
        """Return a json dictionary representing this model."""
        _dict = {}
        if hasattr(self, 'id') and self.id is not None:
            _dict['id'] = self.id
        if hasattr(self, 'primary_node_details') and self.primary_node_details is not None:
            primary_node_details_list = []
            for v in self.primary_node_details:
                if isinstance(v, dict):
                    primary_node_details_list.append(v)
                else:
                    primary_node_details_list.append(v.to_dict())
            _dict['primary_node_details'] = primary_node_details_list
        if hasattr(self, 'secondary_node_details') and self.secondary_node_details is not None:
            secondary_node_details_list = []
            for v in self.secondary_node_details:
                if isinstance(v, dict):
                    secondary_node_details_list.append(v)
                else:
                    secondary_node_details_list.append(v.to_dict())
            _dict['secondary_node_details'] = secondary_node_details_list
        return _dict

    def _to_dict(self):
        """Return a json dictionary representing this model."""
        return self.to_dict()

    def __str__(self) -> str:
        """Return a `str` version of this ClusterNodeResponse object."""
        return json.dumps(self.to_dict(), indent=2)

    def __eq__(self, other: 'ClusterNodeResponse') -> bool:
        """Return `true` when self and other are equal, false otherwise."""
        if not isinstance(other, self.__class__):
            return False
        return self.__dict__ == other.__dict__

    def __ne__(self, other: 'ClusterNodeResponse') -> bool:
        """Return `true` when self and other are not equal, false otherwise."""
        return not self == other


class NodeDetail:
    """
    Details of a virtual machine (VM) participating in the cluster.

    :param str agent_status: (optional) Status of the PHA agent running on the node.
    :param float cores: (optional) Number of CPU cores allocated to the VM.
    :param List[str] ip_addresses: List of IP addresses assigned to the VM.
    :param float memory: (optional) Amount of memory allocated to the VM (in GB).
    :param str pha_level: (optional) PowerHA version level installed on the node.
    :param str region: (optional) Region where the VM is deployed.
    :param str vm_id: (optional) Unique identifier of the VM.
    :param str vm_name: (optional) Name of the VM.
    :param str vm_status: (optional) Current status of the VM.
    :param str workspace_id: (optional) ID of the workspace associated with the VM.
    """

    def __init__(
        self,
        ip_addresses: List[str],
        *,
        agent_status: Optional[str] = None,
        cores: Optional[float] = None,
        memory: Optional[float] = None,
        pha_level: Optional[str] = None,
        region: Optional[str] = None,
        vm_id: Optional[str] = None,
        vm_name: Optional[str] = None,
        vm_status: Optional[str] = None,
        workspace_id: Optional[str] = None,
    ) -> None:
        """
        Initialize a NodeDetail object.

        :param List[str] ip_addresses: List of IP addresses assigned to the VM.
        :param str agent_status: (optional) Status of the PHA agent running on the
               node.
        :param float cores: (optional) Number of CPU cores allocated to the VM.
        :param float memory: (optional) Amount of memory allocated to the VM (in
               GB).
        :param str pha_level: (optional) PowerHA version level installed on the
               node.
        :param str region: (optional) Region where the VM is deployed.
        :param str vm_id: (optional) Unique identifier of the VM.
        :param str vm_name: (optional) Name of the VM.
        :param str vm_status: (optional) Current status of the VM.
        :param str workspace_id: (optional) ID of the workspace associated with the
               VM.
        """
        self.agent_status = agent_status
        self.cores = cores
        self.ip_addresses = ip_addresses
        self.memory = memory
        self.pha_level = pha_level
        self.region = region
        self.vm_id = vm_id
        self.vm_name = vm_name
        self.vm_status = vm_status
        self.workspace_id = workspace_id

    @classmethod
    def from_dict(cls, _dict: Dict) -> 'NodeDetail':
        """Initialize a NodeDetail object from a json dictionary."""
        args = {}
        if (agent_status := _dict.get('agent_status')) is not None:
            args['agent_status'] = agent_status
        if (cores := _dict.get('cores')) is not None:
            args['cores'] = cores
        if (ip_addresses := _dict.get('ip_addresses')) is not None:
            args['ip_addresses'] = ip_addresses
        else:
            raise ValueError('Required property \'ip_addresses\' not present in NodeDetail JSON')
        if (memory := _dict.get('memory')) is not None:
            args['memory'] = memory
        if (pha_level := _dict.get('pha_level')) is not None:
            args['pha_level'] = pha_level
        if (region := _dict.get('region')) is not None:
            args['region'] = region
        if (vm_id := _dict.get('vm_id')) is not None:
            args['vm_id'] = vm_id
        if (vm_name := _dict.get('vm_name')) is not None:
            args['vm_name'] = vm_name
        if (vm_status := _dict.get('vm_status')) is not None:
            args['vm_status'] = vm_status
        if (workspace_id := _dict.get('workspace_id')) is not None:
            args['workspace_id'] = workspace_id
        return cls(**args)

    @classmethod
    def _from_dict(cls, _dict):
        """Initialize a NodeDetail object from a json dictionary."""
        return cls.from_dict(_dict)

    def to_dict(self) -> Dict:
        """Return a json dictionary representing this model."""
        _dict = {}
        if hasattr(self, 'agent_status') and self.agent_status is not None:
            _dict['agent_status'] = self.agent_status
        if hasattr(self, 'cores') and self.cores is not None:
            _dict['cores'] = self.cores
        if hasattr(self, 'ip_addresses') and self.ip_addresses is not None:
            _dict['ip_addresses'] = self.ip_addresses
        if hasattr(self, 'memory') and self.memory is not None:
            _dict['memory'] = self.memory
        if hasattr(self, 'pha_level') and self.pha_level is not None:
            _dict['pha_level'] = self.pha_level
        if hasattr(self, 'region') and self.region is not None:
            _dict['region'] = self.region
        if hasattr(self, 'vm_id') and self.vm_id is not None:
            _dict['vm_id'] = self.vm_id
        if hasattr(self, 'vm_name') and self.vm_name is not None:
            _dict['vm_name'] = self.vm_name
        if hasattr(self, 'vm_status') and self.vm_status is not None:
            _dict['vm_status'] = self.vm_status
        if hasattr(self, 'workspace_id') and self.workspace_id is not None:
            _dict['workspace_id'] = self.workspace_id
        return _dict

    def _to_dict(self):
        """Return a json dictionary representing this model."""
        return self.to_dict()

    def __str__(self) -> str:
        """Return a `str` version of this NodeDetail object."""
        return json.dumps(self.to_dict(), indent=2)

    def __eq__(self, other: 'NodeDetail') -> bool:
        """Return `true` when self and other are equal, false otherwise."""
        if not isinstance(other, self.__class__):
            return False
        return self.__dict__ == other.__dict__

    def __ne__(self, other: 'NodeDetail') -> bool:
        """Return `true` when self and other are not equal, false otherwise."""
        return not self == other


class PhaAgentJobStatusResponse:
    """
    Status information of a PowerHA agent job.

    :param int bytes_downloaded: (optional) Number of bytes downloaded so far.
    :param datetime creation_at: (optional) Timestamp when the job was created.
    :param str file_name: (optional) Name of the file that has been downloaded.
    :param str job_id: (optional) Unique identifier of the job.
    :param datetime last_updated_at: (optional) Timestamp of the last update for
          this status.
    :param str service_instance_id: (optional) Identifier of the service instance
          associated with the deployment.
    :param str status: (optional) Current status of the deployment.
    :param int total_bytes: (optional) Total size in bytes of the file that has to
          be downloaded.
    :param str vm_id: (optional) Identifier of the virtual machine involved in the
          deployment.
    """

    def __init__(
        self,
        *,
        bytes_downloaded: Optional[int] = None,
        creation_at: Optional[datetime] = None,
        file_name: Optional[str] = None,
        job_id: Optional[str] = None,
        last_updated_at: Optional[datetime] = None,
        service_instance_id: Optional[str] = None,
        status: Optional[str] = None,
        total_bytes: Optional[int] = None,
        vm_id: Optional[str] = None,
    ) -> None:
        """
        Initialize a PhaAgentJobStatusResponse object.

        :param int bytes_downloaded: (optional) Number of bytes downloaded so far.
        :param datetime creation_at: (optional) Timestamp when the job was created.
        :param str file_name: (optional) Name of the file that has been downloaded.
        :param str job_id: (optional) Unique identifier of the job.
        :param datetime last_updated_at: (optional) Timestamp of the last update
               for this status.
        :param str service_instance_id: (optional) Identifier of the service
               instance associated with the deployment.
        :param str status: (optional) Current status of the deployment.
        :param int total_bytes: (optional) Total size in bytes of the file that has
               to be downloaded.
        :param str vm_id: (optional) Identifier of the virtual machine involved in
               the deployment.
        """
        self.bytes_downloaded = bytes_downloaded
        self.creation_at = creation_at
        self.file_name = file_name
        self.job_id = job_id
        self.last_updated_at = last_updated_at
        self.service_instance_id = service_instance_id
        self.status = status
        self.total_bytes = total_bytes
        self.vm_id = vm_id

    @classmethod
    def from_dict(cls, _dict: Dict) -> 'PhaAgentJobStatusResponse':
        """Initialize a PhaAgentJobStatusResponse object from a json dictionary."""
        args = {}
        if (bytes_downloaded := _dict.get('bytes_downloaded')) is not None:
            args['bytes_downloaded'] = bytes_downloaded
        if (creation_at := _dict.get('creation_at')) is not None:
            args['creation_at'] = string_to_datetime(creation_at)
        if (file_name := _dict.get('file_name')) is not None:
            args['file_name'] = file_name
        if (job_id := _dict.get('job_id')) is not None:
            args['job_id'] = job_id
        if (last_updated_at := _dict.get('last_updated_at')) is not None:
            args['last_updated_at'] = string_to_datetime(last_updated_at)
        if (service_instance_id := _dict.get('service_instance_id')) is not None:
            args['service_instance_id'] = service_instance_id
        if (status := _dict.get('status')) is not None:
            args['status'] = status
        if (total_bytes := _dict.get('total_bytes')) is not None:
            args['total_bytes'] = total_bytes
        if (vm_id := _dict.get('vm_id')) is not None:
            args['vm_id'] = vm_id
        return cls(**args)

    @classmethod
    def _from_dict(cls, _dict):
        """Initialize a PhaAgentJobStatusResponse object from a json dictionary."""
        return cls.from_dict(_dict)

    def to_dict(self) -> Dict:
        """Return a json dictionary representing this model."""
        _dict = {}
        if hasattr(self, 'bytes_downloaded') and self.bytes_downloaded is not None:
            _dict['bytes_downloaded'] = self.bytes_downloaded
        if hasattr(self, 'creation_at') and self.creation_at is not None:
            _dict['creation_at'] = datetime_to_string(self.creation_at)
        if hasattr(self, 'file_name') and self.file_name is not None:
            _dict['file_name'] = self.file_name
        if hasattr(self, 'job_id') and self.job_id is not None:
            _dict['job_id'] = self.job_id
        if hasattr(self, 'last_updated_at') and self.last_updated_at is not None:
            _dict['last_updated_at'] = datetime_to_string(self.last_updated_at)
        if hasattr(self, 'service_instance_id') and self.service_instance_id is not None:
            _dict['service_instance_id'] = self.service_instance_id
        if hasattr(self, 'status') and self.status is not None:
            _dict['status'] = self.status
        if hasattr(self, 'total_bytes') and self.total_bytes is not None:
            _dict['total_bytes'] = self.total_bytes
        if hasattr(self, 'vm_id') and self.vm_id is not None:
            _dict['vm_id'] = self.vm_id
        return _dict

    def _to_dict(self):
        """Return a json dictionary representing this model."""
        return self.to_dict()

    def __str__(self) -> str:
        """Return a `str` version of this PhaAgentJobStatusResponse object."""
        return json.dumps(self.to_dict(), indent=2)

    def __eq__(self, other: 'PhaAgentJobStatusResponse') -> bool:
        """Return `true` when self and other are equal, false otherwise."""
        if not isinstance(other, self.__class__):
            return False
        return self.__dict__ == other.__dict__

    def __ne__(self, other: 'PhaAgentJobStatusResponse') -> bool:
        """Return `true` when self and other are not equal, false otherwise."""
        return not self == other


class PhaDeploymentResponse:
    """
    Details of a PowerHA deployment including cluster information, provisioning status,
    network configuration, and associated resources.

    :param str cloud_account_id: (optional) Cloud account identifier.
    :param str connectivity_type: (optional) Type of network connectivity.
    :param str creation_time: (optional) Timestamp expressing creation time.
    :param List[str] custom_network: List of custom network CIDRs.
    :param str deprovision_time: (optional) Timestamp expressing deprovision time.
    :param str guid: (optional) Global unique identifier.
    :param bool is_duplicate: (optional) Indicates whether deployment is duplicate.
    :param str plan_id: (optional) Identifier for the service plan.
    :param str plan_name: (optional) Name of service plan.
    :param str powerha_cluster_name: (optional) Name of the PowerHA cluster.
    :param str powerha_cluster_type: (optional) Type of PowerHA cluster.
    :param str powerha_level: (optional) PowerHA version level.
    :param List[ClusterNodeInfo] primary_cluster_nodes_details: List of primary
          cluster nodes.
    :param str primary_location: (optional) Primary cluster location.
    :param str primary_region_name: (optional) name of the primary workspace region.
    :param str primary_workspace: (optional) Primary workspace identifier.
    :param str primary_workspace_name: (optional) name of the primary workspace.
    :param str provision_end_time: (optional) Time stamp provisioning completed.
    :param str id: (optional) Provision request identifier.
    :param str provision_start_time: (optional) Time stamp provisioning started.
    :param str provision_status: (optional) Current provision status.
    :param str region_id: (optional) Deployment region identifier.
    :param str resource_group: (optional) Name of the resource group.
    :param str resource_group_crn: (optional) CRN of associated resource group.
    :param str resource_instance: (optional) Resource instance identifier.
    :param List[ClusterNodeInfo] secondary_cluster_nodes: List of secondary cluster
          nodes.
    :param str secondary_location: (optional) Secondary cluster location.
    :param str secondary_workspace: (optional) Secondary workspace identifier.
    :param str service_description: (optional) Description of provisioned service.
    :param str service_id: (optional) Identifier for the service.
    :param str service_name: (optional) Name of service.
    :param str standby_region_name: (optional) name of the standby workspace region.
    :param str standby_workspace_name: (optional) name of the standby workspace.
    :param str user_tags: (optional) User defined tags.
    """

    def __init__(
        self,
        custom_network: List[str],
        primary_cluster_nodes_details: List['ClusterNodeInfo'],
        secondary_cluster_nodes: List['ClusterNodeInfo'],
        *,
        cloud_account_id: Optional[str] = None,
        connectivity_type: Optional[str] = None,
        creation_time: Optional[str] = None,
        deprovision_time: Optional[str] = None,
        guid: Optional[str] = None,
        is_duplicate: Optional[bool] = None,
        plan_id: Optional[str] = None,
        plan_name: Optional[str] = None,
        powerha_cluster_name: Optional[str] = None,
        powerha_cluster_type: Optional[str] = None,
        powerha_level: Optional[str] = None,
        primary_location: Optional[str] = None,
        primary_region_name: Optional[str] = None,
        primary_workspace: Optional[str] = None,
        primary_workspace_name: Optional[str] = None,
        provision_end_time: Optional[str] = None,
        id: Optional[str] = None,
        provision_start_time: Optional[str] = None,
        provision_status: Optional[str] = None,
        region_id: Optional[str] = None,
        resource_group: Optional[str] = None,
        resource_group_crn: Optional[str] = None,
        resource_instance: Optional[str] = None,
        secondary_location: Optional[str] = None,
        secondary_workspace: Optional[str] = None,
        service_description: Optional[str] = None,
        service_id: Optional[str] = None,
        service_name: Optional[str] = None,
        standby_region_name: Optional[str] = None,
        standby_workspace_name: Optional[str] = None,
        user_tags: Optional[str] = None,
    ) -> None:
        """
        Initialize a PhaDeploymentResponse object.

        :param List[str] custom_network: List of custom network CIDRs.
        :param List[ClusterNodeInfo] primary_cluster_nodes_details: List of primary
               cluster nodes.
        :param List[ClusterNodeInfo] secondary_cluster_nodes: List of secondary
               cluster nodes.
        :param str cloud_account_id: (optional) Cloud account identifier.
        :param str connectivity_type: (optional) Type of network connectivity.
        :param str creation_time: (optional) Timestamp expressing creation time.
        :param str deprovision_time: (optional) Timestamp expressing deprovision
               time.
        :param str guid: (optional) Global unique identifier.
        :param bool is_duplicate: (optional) Indicates whether deployment is
               duplicate.
        :param str plan_id: (optional) Identifier for the service plan.
        :param str plan_name: (optional) Name of service plan.
        :param str powerha_cluster_name: (optional) Name of the PowerHA cluster.
        :param str powerha_cluster_type: (optional) Type of PowerHA cluster.
        :param str powerha_level: (optional) PowerHA version level.
        :param str primary_location: (optional) Primary cluster location.
        :param str primary_region_name: (optional) name of the primary workspace
               region.
        :param str primary_workspace: (optional) Primary workspace identifier.
        :param str primary_workspace_name: (optional) name of the primary
               workspace.
        :param str provision_end_time: (optional) Time stamp provisioning
               completed.
        :param str id: (optional) Provision request identifier.
        :param str provision_start_time: (optional) Time stamp provisioning
               started.
        :param str provision_status: (optional) Current provision status.
        :param str region_id: (optional) Deployment region identifier.
        :param str resource_group: (optional) Name of the resource group.
        :param str resource_group_crn: (optional) CRN of associated resource group.
        :param str resource_instance: (optional) Resource instance identifier.
        :param str secondary_location: (optional) Secondary cluster location.
        :param str secondary_workspace: (optional) Secondary workspace identifier.
        :param str service_description: (optional) Description of provisioned
               service.
        :param str service_id: (optional) Identifier for the service.
        :param str service_name: (optional) Name of service.
        :param str standby_region_name: (optional) name of the standby workspace
               region.
        :param str standby_workspace_name: (optional) name of the standby
               workspace.
        :param str user_tags: (optional) User defined tags.
        """
        self.cloud_account_id = cloud_account_id
        self.connectivity_type = connectivity_type
        self.creation_time = creation_time
        self.custom_network = custom_network
        self.deprovision_time = deprovision_time
        self.guid = guid
        self.is_duplicate = is_duplicate
        self.plan_id = plan_id
        self.plan_name = plan_name
        self.powerha_cluster_name = powerha_cluster_name
        self.powerha_cluster_type = powerha_cluster_type
        self.powerha_level = powerha_level
        self.primary_cluster_nodes_details = primary_cluster_nodes_details
        self.primary_location = primary_location
        self.primary_region_name = primary_region_name
        self.primary_workspace = primary_workspace
        self.primary_workspace_name = primary_workspace_name
        self.provision_end_time = provision_end_time
        self.id = id
        self.provision_start_time = provision_start_time
        self.provision_status = provision_status
        self.region_id = region_id
        self.resource_group = resource_group
        self.resource_group_crn = resource_group_crn
        self.resource_instance = resource_instance
        self.secondary_cluster_nodes = secondary_cluster_nodes
        self.secondary_location = secondary_location
        self.secondary_workspace = secondary_workspace
        self.service_description = service_description
        self.service_id = service_id
        self.service_name = service_name
        self.standby_region_name = standby_region_name
        self.standby_workspace_name = standby_workspace_name
        self.user_tags = user_tags

    @classmethod
    def from_dict(cls, _dict: Dict) -> 'PhaDeploymentResponse':
        """Initialize a PhaDeploymentResponse object from a json dictionary."""
        args = {}
        if (cloud_account_id := _dict.get('cloud_account_id')) is not None:
            args['cloud_account_id'] = cloud_account_id
        if (connectivity_type := _dict.get('connectivity_type')) is not None:
            args['connectivity_type'] = connectivity_type
        if (creation_time := _dict.get('creation_time')) is not None:
            args['creation_time'] = creation_time
        if (custom_network := _dict.get('custom_network')) is not None:
            args['custom_network'] = custom_network
        else:
            raise ValueError('Required property \'custom_network\' not present in PhaDeploymentResponse JSON')
        if (deprovision_time := _dict.get('deprovision_time')) is not None:
            args['deprovision_time'] = deprovision_time
        if (guid := _dict.get('guid')) is not None:
            args['guid'] = guid
        if (is_duplicate := _dict.get('is_duplicate')) is not None:
            args['is_duplicate'] = is_duplicate
        if (plan_id := _dict.get('plan_id')) is not None:
            args['plan_id'] = plan_id
        if (plan_name := _dict.get('plan_name')) is not None:
            args['plan_name'] = plan_name
        if (powerha_cluster_name := _dict.get('powerha_cluster_name')) is not None:
            args['powerha_cluster_name'] = powerha_cluster_name
        if (powerha_cluster_type := _dict.get('powerha_cluster_type')) is not None:
            args['powerha_cluster_type'] = powerha_cluster_type
        if (powerha_level := _dict.get('powerha_level')) is not None:
            args['powerha_level'] = powerha_level
        if (primary_cluster_nodes_details := _dict.get('primary_cluster_nodes_details')) is not None:
            args['primary_cluster_nodes_details'] = [
                ClusterNodeInfo.from_dict(v) for v in primary_cluster_nodes_details
            ]
        else:
            raise ValueError(
                'Required property \'primary_cluster_nodes_details\' not present in PhaDeploymentResponse JSON'
            )
        if (primary_location := _dict.get('primary_location')) is not None:
            args['primary_location'] = primary_location
        if (primary_region_name := _dict.get('primary_region_name')) is not None:
            args['primary_region_name'] = primary_region_name
        if (primary_workspace := _dict.get('primary_workspace')) is not None:
            args['primary_workspace'] = primary_workspace
        if (primary_workspace_name := _dict.get('primary_workspace_name')) is not None:
            args['primary_workspace_name'] = primary_workspace_name
        if (provision_end_time := _dict.get('provision_end_time')) is not None:
            args['provision_end_time'] = provision_end_time
        if (id := _dict.get('id')) is not None:
            args['id'] = id
        if (provision_start_time := _dict.get('provision_start_time')) is not None:
            args['provision_start_time'] = provision_start_time
        if (provision_status := _dict.get('provision_status')) is not None:
            args['provision_status'] = provision_status
        if (region_id := _dict.get('region_id')) is not None:
            args['region_id'] = region_id
        if (resource_group := _dict.get('resource_group')) is not None:
            args['resource_group'] = resource_group
        if (resource_group_crn := _dict.get('resource_group_crn')) is not None:
            args['resource_group_crn'] = resource_group_crn
        if (resource_instance := _dict.get('resource_instance')) is not None:
            args['resource_instance'] = resource_instance
        if (secondary_cluster_nodes := _dict.get('secondary_cluster_nodes')) is not None:
            args['secondary_cluster_nodes'] = [ClusterNodeInfo.from_dict(v) for v in secondary_cluster_nodes]
        else:
            raise ValueError('Required property \'secondary_cluster_nodes\' not present in PhaDeploymentResponse JSON')
        if (secondary_location := _dict.get('secondary_location')) is not None:
            args['secondary_location'] = secondary_location
        if (secondary_workspace := _dict.get('secondary_workspace')) is not None:
            args['secondary_workspace'] = secondary_workspace
        if (service_description := _dict.get('service_description')) is not None:
            args['service_description'] = service_description
        if (service_id := _dict.get('service_id')) is not None:
            args['service_id'] = service_id
        if (service_name := _dict.get('service_name')) is not None:
            args['service_name'] = service_name
        if (standby_region_name := _dict.get('standby_region_name')) is not None:
            args['standby_region_name'] = standby_region_name
        if (standby_workspace_name := _dict.get('standby_workspace_name')) is not None:
            args['standby_workspace_name'] = standby_workspace_name
        if (user_tags := _dict.get('user_tags')) is not None:
            args['user_tags'] = user_tags
        return cls(**args)

    @classmethod
    def _from_dict(cls, _dict):
        """Initialize a PhaDeploymentResponse object from a json dictionary."""
        return cls.from_dict(_dict)

    def to_dict(self) -> Dict:
        """Return a json dictionary representing this model."""
        _dict = {}
        if hasattr(self, 'cloud_account_id') and self.cloud_account_id is not None:
            _dict['cloud_account_id'] = self.cloud_account_id
        if hasattr(self, 'connectivity_type') and self.connectivity_type is not None:
            _dict['connectivity_type'] = self.connectivity_type
        if hasattr(self, 'creation_time') and self.creation_time is not None:
            _dict['creation_time'] = self.creation_time
        if hasattr(self, 'custom_network') and self.custom_network is not None:
            _dict['custom_network'] = self.custom_network
        if hasattr(self, 'deprovision_time') and self.deprovision_time is not None:
            _dict['deprovision_time'] = self.deprovision_time
        if hasattr(self, 'guid') and self.guid is not None:
            _dict['guid'] = self.guid
        if hasattr(self, 'is_duplicate') and self.is_duplicate is not None:
            _dict['is_duplicate'] = self.is_duplicate
        if hasattr(self, 'plan_id') and self.plan_id is not None:
            _dict['plan_id'] = self.plan_id
        if hasattr(self, 'plan_name') and self.plan_name is not None:
            _dict['plan_name'] = self.plan_name
        if hasattr(self, 'powerha_cluster_name') and self.powerha_cluster_name is not None:
            _dict['powerha_cluster_name'] = self.powerha_cluster_name
        if hasattr(self, 'powerha_cluster_type') and self.powerha_cluster_type is not None:
            _dict['powerha_cluster_type'] = self.powerha_cluster_type
        if hasattr(self, 'powerha_level') and self.powerha_level is not None:
            _dict['powerha_level'] = self.powerha_level
        if hasattr(self, 'primary_cluster_nodes_details') and self.primary_cluster_nodes_details is not None:
            primary_cluster_nodes_details_list = []
            for v in self.primary_cluster_nodes_details:
                if isinstance(v, dict):
                    primary_cluster_nodes_details_list.append(v)
                else:
                    primary_cluster_nodes_details_list.append(v.to_dict())
            _dict['primary_cluster_nodes_details'] = primary_cluster_nodes_details_list
        if hasattr(self, 'primary_location') and self.primary_location is not None:
            _dict['primary_location'] = self.primary_location
        if hasattr(self, 'primary_region_name') and self.primary_region_name is not None:
            _dict['primary_region_name'] = self.primary_region_name
        if hasattr(self, 'primary_workspace') and self.primary_workspace is not None:
            _dict['primary_workspace'] = self.primary_workspace
        if hasattr(self, 'primary_workspace_name') and self.primary_workspace_name is not None:
            _dict['primary_workspace_name'] = self.primary_workspace_name
        if hasattr(self, 'provision_end_time') and self.provision_end_time is not None:
            _dict['provision_end_time'] = self.provision_end_time
        if hasattr(self, 'id') and self.id is not None:
            _dict['id'] = self.id
        if hasattr(self, 'provision_start_time') and self.provision_start_time is not None:
            _dict['provision_start_time'] = self.provision_start_time
        if hasattr(self, 'provision_status') and self.provision_status is not None:
            _dict['provision_status'] = self.provision_status
        if hasattr(self, 'region_id') and self.region_id is not None:
            _dict['region_id'] = self.region_id
        if hasattr(self, 'resource_group') and self.resource_group is not None:
            _dict['resource_group'] = self.resource_group
        if hasattr(self, 'resource_group_crn') and self.resource_group_crn is not None:
            _dict['resource_group_crn'] = self.resource_group_crn
        if hasattr(self, 'resource_instance') and self.resource_instance is not None:
            _dict['resource_instance'] = self.resource_instance
        if hasattr(self, 'secondary_cluster_nodes') and self.secondary_cluster_nodes is not None:
            secondary_cluster_nodes_list = []
            for v in self.secondary_cluster_nodes:
                if isinstance(v, dict):
                    secondary_cluster_nodes_list.append(v)
                else:
                    secondary_cluster_nodes_list.append(v.to_dict())
            _dict['secondary_cluster_nodes'] = secondary_cluster_nodes_list
        if hasattr(self, 'secondary_location') and self.secondary_location is not None:
            _dict['secondary_location'] = self.secondary_location
        if hasattr(self, 'secondary_workspace') and self.secondary_workspace is not None:
            _dict['secondary_workspace'] = self.secondary_workspace
        if hasattr(self, 'service_description') and self.service_description is not None:
            _dict['service_description'] = self.service_description
        if hasattr(self, 'service_id') and self.service_id is not None:
            _dict['service_id'] = self.service_id
        if hasattr(self, 'service_name') and self.service_name is not None:
            _dict['service_name'] = self.service_name
        if hasattr(self, 'standby_region_name') and self.standby_region_name is not None:
            _dict['standby_region_name'] = self.standby_region_name
        if hasattr(self, 'standby_workspace_name') and self.standby_workspace_name is not None:
            _dict['standby_workspace_name'] = self.standby_workspace_name
        if hasattr(self, 'user_tags') and self.user_tags is not None:
            _dict['user_tags'] = self.user_tags
        return _dict

    def _to_dict(self):
        """Return a json dictionary representing this model."""
        return self.to_dict()

    def __str__(self) -> str:
        """Return a `str` version of this PhaDeploymentResponse object."""
        return json.dumps(self.to_dict(), indent=2)

    def __eq__(self, other: 'PhaDeploymentResponse') -> bool:
        """Return `true` when self and other are equal, false otherwise."""
        if not isinstance(other, self.__class__):
            return False
        return self.__dict__ == other.__dict__

    def __ne__(self, other: 'PhaDeploymentResponse') -> bool:
        """Return `true` when self and other are not equal, false otherwise."""
        return not self == other


class PhaLocation:
    """
    Details of a PowerHA supported location.

    :param str id: (optional) Unique identifier for the location.
    :param str name: (optional) Human-readable name of the location.
    """

    def __init__(
        self,
        *,
        id: Optional[str] = None,
        name: Optional[str] = None,
    ) -> None:
        """
        Initialize a PhaLocation object.

        :param str id: (optional) Unique identifier for the location.
        :param str name: (optional) Human-readable name of the location.
        """
        self.id = id
        self.name = name

    @classmethod
    def from_dict(cls, _dict: Dict) -> 'PhaLocation':
        """Initialize a PhaLocation object from a json dictionary."""
        args = {}
        if (id := _dict.get('id')) is not None:
            args['id'] = id
        if (name := _dict.get('name')) is not None:
            args['name'] = name
        return cls(**args)

    @classmethod
    def _from_dict(cls, _dict):
        """Initialize a PhaLocation object from a json dictionary."""
        return cls.from_dict(_dict)

    def to_dict(self) -> Dict:
        """Return a json dictionary representing this model."""
        _dict = {}
        if hasattr(self, 'id') and self.id is not None:
            _dict['id'] = self.id
        if hasattr(self, 'name') and self.name is not None:
            _dict['name'] = self.name
        return _dict

    def _to_dict(self):
        """Return a json dictionary representing this model."""
        return self.to_dict()

    def __str__(self) -> str:
        """Return a `str` version of this PhaLocation object."""
        return json.dumps(self.to_dict(), indent=2)

    def __eq__(self, other: 'PhaLocation') -> bool:
        """Return `true` when self and other are equal, false otherwise."""
        if not isinstance(other, self.__class__):
            return False
        return self.__dict__ == other.__dict__

    def __ne__(self, other: 'PhaLocation') -> bool:
        """Return `true` when self and other are not equal, false otherwise."""
        return not self == other


class PhaSupportedLocationsResponse:
    """
    List of PowerVS locations where PowerHA service is supported.

    :param List[PhaLocation] locations: Array of PowerVS locations where PowerHA
          service is supported.
    """

    def __init__(
        self,
        locations: List['PhaLocation'],
    ) -> None:
        """
        Initialize a PhaSupportedLocationsResponse object.

        :param List[PhaLocation] locations: Array of PowerVS locations where
               PowerHA service is supported.
        """
        self.locations = locations

    @classmethod
    def from_dict(cls, _dict: Dict) -> 'PhaSupportedLocationsResponse':
        """Initialize a PhaSupportedLocationsResponse object from a json dictionary."""
        args = {}
        if (locations := _dict.get('locations')) is not None:
            args['locations'] = [PhaLocation.from_dict(v) for v in locations]
        else:
            raise ValueError('Required property \'locations\' not present in PhaSupportedLocationsResponse JSON')
        return cls(**args)

    @classmethod
    def _from_dict(cls, _dict):
        """Initialize a PhaSupportedLocationsResponse object from a json dictionary."""
        return cls.from_dict(_dict)

    def to_dict(self) -> Dict:
        """Return a json dictionary representing this model."""
        _dict = {}
        if hasattr(self, 'locations') and self.locations is not None:
            locations_list = []
            for v in self.locations:
                if isinstance(v, dict):
                    locations_list.append(v)
                else:
                    locations_list.append(v.to_dict())
            _dict['locations'] = locations_list
        return _dict

    def _to_dict(self):
        """Return a json dictionary representing this model."""
        return self.to_dict()

    def __str__(self) -> str:
        """Return a `str` version of this PhaSupportedLocationsResponse object."""
        return json.dumps(self.to_dict(), indent=2)

    def __eq__(self, other: 'PhaSupportedLocationsResponse') -> bool:
        """Return `true` when self and other are equal, false otherwise."""
        if not isinstance(other, self.__class__):
            return False
        return self.__dict__ == other.__dict__

    def __ne__(self, other: 'PhaSupportedLocationsResponse') -> bool:
        """Return `true` when self and other are not equal, false otherwise."""
        return not self == other


class PhaWorkspaceSummary:
    """
    Summary information for a PowerHA workspace.

    :param str id: (optional) Unique identifier of the workspace.
    :param str name: (optional) Name of the workspace.
    """

    def __init__(
        self,
        *,
        id: Optional[str] = None,
        name: Optional[str] = None,
    ) -> None:
        """
        Initialize a PhaWorkspaceSummary object.

        :param str id: (optional) Unique identifier of the workspace.
        :param str name: (optional) Name of the workspace.
        """
        self.id = id
        self.name = name

    @classmethod
    def from_dict(cls, _dict: Dict) -> 'PhaWorkspaceSummary':
        """Initialize a PhaWorkspaceSummary object from a json dictionary."""
        args = {}
        if (id := _dict.get('id')) is not None:
            args['id'] = id
        if (name := _dict.get('name')) is not None:
            args['name'] = name
        return cls(**args)

    @classmethod
    def _from_dict(cls, _dict):
        """Initialize a PhaWorkspaceSummary object from a json dictionary."""
        return cls.from_dict(_dict)

    def to_dict(self) -> Dict:
        """Return a json dictionary representing this model."""
        _dict = {}
        if hasattr(self, 'id') and self.id is not None:
            _dict['id'] = self.id
        if hasattr(self, 'name') and self.name is not None:
            _dict['name'] = self.name
        return _dict

    def _to_dict(self):
        """Return a json dictionary representing this model."""
        return self.to_dict()

    def __str__(self) -> str:
        """Return a `str` version of this PhaWorkspaceSummary object."""
        return json.dumps(self.to_dict(), indent=2)

    def __eq__(self, other: 'PhaWorkspaceSummary') -> bool:
        """Return `true` when self and other are equal, false otherwise."""
        if not isinstance(other, self.__class__):
            return False
        return self.__dict__ == other.__dict__

    def __ne__(self, other: 'PhaWorkspaceSummary') -> bool:
        """Return `true` when self and other are not equal, false otherwise."""
        return not self == other


class PhaWorkspacesRegionResponse:
    """
    Response containing the list of workspaces for a specific region.

    :param List[PhaWorkspaceSummary] workspaces: Array of workspace summaries within
          the region.
    """

    def __init__(
        self,
        workspaces: List['PhaWorkspaceSummary'],
    ) -> None:
        """
        Initialize a PhaWorkspacesRegionResponse object.

        :param List[PhaWorkspaceSummary] workspaces: Array of workspace summaries
               within the region.
        """
        self.workspaces = workspaces

    @classmethod
    def from_dict(cls, _dict: Dict) -> 'PhaWorkspacesRegionResponse':
        """Initialize a PhaWorkspacesRegionResponse object from a json dictionary."""
        args = {}
        if (workspaces := _dict.get('workspaces')) is not None:
            args['workspaces'] = [PhaWorkspaceSummary.from_dict(v) for v in workspaces]
        else:
            raise ValueError('Required property \'workspaces\' not present in PhaWorkspacesRegionResponse JSON')
        return cls(**args)

    @classmethod
    def _from_dict(cls, _dict):
        """Initialize a PhaWorkspacesRegionResponse object from a json dictionary."""
        return cls.from_dict(_dict)

    def to_dict(self) -> Dict:
        """Return a json dictionary representing this model."""
        _dict = {}
        if hasattr(self, 'workspaces') and self.workspaces is not None:
            workspaces_list = []
            for v in self.workspaces:
                if isinstance(v, dict):
                    workspaces_list.append(v)
                else:
                    workspaces_list.append(v.to_dict())
            _dict['workspaces'] = workspaces_list
        return _dict

    def _to_dict(self):
        """Return a json dictionary representing this model."""
        return self.to_dict()

    def __str__(self) -> str:
        """Return a `str` version of this PhaWorkspacesRegionResponse object."""
        return json.dumps(self.to_dict(), indent=2)

    def __eq__(self, other: 'PhaWorkspacesRegionResponse') -> bool:
        """Return `true` when self and other are equal, false otherwise."""
        if not isinstance(other, self.__class__):
            return False
        return self.__dict__ == other.__dict__

    def __ne__(self, other: 'PhaWorkspacesRegionResponse') -> bool:
        """Return `true` when self and other are not equal, false otherwise."""
        return not self == other


class ServiceInstancePhaStatus:
    """
    Current status information for a PHA service instance.

    :param str deployment_name: Name of the deployment associated with the service
          instance.
    :param str provision_id: Unique identifier for the provisioning operation.
    :param str resource_group: Resource Group.
    :param str status: Current operational status of the service instance.
    """

    def __init__(
        self,
        deployment_name: str,
        provision_id: str,
        resource_group: str,
        status: str,
    ) -> None:
        """
        Initialize a ServiceInstancePhaStatus object.

        :param str deployment_name: Name of the deployment associated with the
               service instance.
        :param str provision_id: Unique identifier for the provisioning operation.
        :param str resource_group: Resource Group.
        :param str status: Current operational status of the service instance.
        """
        self.deployment_name = deployment_name
        self.provision_id = provision_id
        self.resource_group = resource_group
        self.status = status

    @classmethod
    def from_dict(cls, _dict: Dict) -> 'ServiceInstancePhaStatus':
        """Initialize a ServiceInstancePhaStatus object from a json dictionary."""
        args = {}
        if (deployment_name := _dict.get('deployment_name')) is not None:
            args['deployment_name'] = deployment_name
        else:
            raise ValueError('Required property \'deployment_name\' not present in ServiceInstancePhaStatus JSON')
        if (provision_id := _dict.get('provision_id')) is not None:
            args['provision_id'] = provision_id
        else:
            raise ValueError('Required property \'provision_id\' not present in ServiceInstancePhaStatus JSON')
        if (resource_group := _dict.get('resource_group')) is not None:
            args['resource_group'] = resource_group
        else:
            raise ValueError('Required property \'resource_group\' not present in ServiceInstancePhaStatus JSON')
        if (status := _dict.get('status')) is not None:
            args['status'] = status
        else:
            raise ValueError('Required property \'status\' not present in ServiceInstancePhaStatus JSON')
        return cls(**args)

    @classmethod
    def _from_dict(cls, _dict):
        """Initialize a ServiceInstancePhaStatus object from a json dictionary."""
        return cls.from_dict(_dict)

    def to_dict(self) -> Dict:
        """Return a json dictionary representing this model."""
        _dict = {}
        if hasattr(self, 'deployment_name') and self.deployment_name is not None:
            _dict['deployment_name'] = self.deployment_name
        if hasattr(self, 'provision_id') and self.provision_id is not None:
            _dict['provision_id'] = self.provision_id
        if hasattr(self, 'resource_group') and self.resource_group is not None:
            _dict['resource_group'] = self.resource_group
        if hasattr(self, 'status') and self.status is not None:
            _dict['status'] = self.status
        return _dict

    def _to_dict(self):
        """Return a json dictionary representing this model."""
        return self.to_dict()

    def __str__(self) -> str:
        """Return a `str` version of this ServiceInstancePhaStatus object."""
        return json.dumps(self.to_dict(), indent=2)

    def __eq__(self, other: 'ServiceInstancePhaStatus') -> bool:
        """Return `true` when self and other are equal, false otherwise."""
        if not isinstance(other, self.__class__):
            return False
        return self.__dict__ == other.__dict__

    def __ne__(self, other: 'ServiceInstancePhaStatus') -> bool:
        """Return `true` when self and other are not equal, false otherwise."""
        return not self == other
